
services:

  app:

    depends_on:
      - db
      - mongo-express
    build: .
    # target: ${STAGE}
    # dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules

    container_name: journal_back
    ports:
      - ${PORT}:${PORT}
    restart: always
    environment:
      MONGODB: mongodb://${DB_USERNAME}:${DB_PASSWORD}@host.docker.internal:27018
      APP_VERSION: ${APP_VERSION}
      STAGE: ${STAGE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: host.docker.internal
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      PORT: ${PORT}

  db:
    container_name: ${DB_NAME}
    image: mongo:7.0
    volumes: 
      - diary_vol:/data/db
    ports:
      - ${DB_PORT}:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_REPLICA_HOST: host.docker.internal
    command: ['--auth']

  mongo-express:
    depends_on:
      - db
    image: mongo-express:1.0.0-alpha.4
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${DB_NAME} 
    ports:
      - 8081:8081
    restart: always

volumes:
  diary_vol:
    external: false


